### ISSUE TITLE
Menu-Bar her bir sayfada ayrıca tanımlanmış

### ISSUE THREAD

**Issue by mregungor** [mregungor/web#1]
Bütün menüler tek bir html sayfasından javascript ile çekilmeli.
Örnek link:
[https://stackoverflow.com/questions/38837835/include-html-in-another-html-file](https://stackoverflow.com/questions/38837835/include-html-in-another-html-file) 
-Edit-

**Comment by mertseyit** [comment]
tamam bakıyorum hocam

**Comment by mertseyit** [comment]
Hata çözüldü

**Comment by mertseyit** [comment]
Hata çözüldü
