### ISSUE TITLE
TODO: Online C Compiler

### ISSUE THREAD

**Issue by mregungor** [mregungor/web#2]
Online C compiler link olarak veya frame olarak eklenecek.
Algoritma ve Programlama dersinin içeriğine eklenebilir.

[https://www.onlinegdb.com/online_c_compiler](https://www.onlinegdb.com/online_c_compiler)
veya integrated c compiler olabilir herhangi güvenilir bir siteden.

**Comment by mertseyit** [comment]
Halledildi
